# TCL File Generated by Component Editor 13.1
# Sat Nov 16 20:05:18 CET 2013
# DO NOT MODIFY


# 
# rgb_matrix "rgb_matrix" v0.9.1
# dasdgw 2013.11.16.20:05:18
# led rgbmatrix 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module rgb_matrix
# 
set_module_property DESCRIPTION "led rgbmatrix "
set_module_property NAME rgb_matrix
set_module_property VERSION 0.9.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP frankalicious
set_module_property AUTHOR dasdgw
set_module_property DISPLAY_NAME rgb_matrix
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avs_rgbmatrix
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file rgbmatrix_pkg.vhd VHDL PATH ../vhdl/rgbmatrix_pkg.vhd
add_fileset_file ledctrl.vhd VHDL PATH ../vhdl/ledctrl.vhd
add_fileset_file i2c_memory.vhd VHDL PATH ../vhdl/i2c_memory.vhd
add_fileset_file jtag_iface.vhd VHDL PATH ../vhdl/jtag_iface.vhd
add_fileset_file jtag_memory.vhd VHDL PATH ../vhdl/jtag_memory.vhd
add_fileset_file megawizard_vjtag.vhd VHDL PATH ../vhdl/megawizard/megawizard_vjtag.vhd
add_fileset_file i2c_slave.vhd VHDL PATH ../vhdl/i2c_slave.vhd
add_fileset_file avs_rgbmatrix.vhd VHDL PATH ../vhdl/avs_rgbmatrix.vhd TOP_LEVEL_FILE
add_fileset_file avs_memory.vhd VHDL PATH ../vhdl/avs_memory.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_s0_waitrequest waitrequest Output 1
add_interface_port avalon_slave_0 avs_s0_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_s0_read read Input 1
add_interface_port avalon_slave_0 avs_s0_address address Input 8
add_interface_port avalon_slave_0 avs_s0_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_s0_write write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end g1 export Output 1
add_interface_port conduit_end g2 export Output 1
add_interface_port conduit_end a export Output 1
add_interface_port conduit_end b export Output 1
add_interface_port conduit_end lat export Output 1
add_interface_port conduit_end c export Output 1
add_interface_port conduit_end oe export Output 1
add_interface_port conduit_end r1 export Output 1
add_interface_port conduit_end r2 export Output 1
add_interface_port conduit_end b1 export Output 1
add_interface_port conduit_end b2 export Output 1


# 
# connection point clock_source
# 
add_interface clock_source clock start
set_interface_property clock_source associatedDirectClock ""
set_interface_property clock_source clockRate 0
set_interface_property clock_source clockRateKnown false
set_interface_property clock_source ENABLED true
set_interface_property clock_source EXPORT_OF ""
set_interface_property clock_source PORT_NAME_MAP ""
set_interface_property clock_source CMSIS_SVD_VARIABLES ""
set_interface_property clock_source SVD_ADDRESS_GROUP ""

add_interface_port clock_source clk_out clk Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_led clk Input 1

